/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.biblioteca.view;

/**
 *
 * @author me
 */
public class InsertLoanView extends javax.swing.JPanel {

    /**
     * Creates new form InsertLoanView
     */
    public InsertLoanView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTituloDePagina = new javax.swing.JLabel();
        txtIdentificacion = new javax.swing.JTextField();
        txtPrestamo = new javax.swing.JTextField();
        txtIsbn = new javax.swing.JTextField();
        txtEntrega = new javax.swing.JTextField();
        lblIsbn = new javax.swing.JLabel();
        lblIdentificacion = new javax.swing.JLabel();
        lblPrestamo = new javax.swing.JLabel();
        lblEntregar = new javax.swing.JLabel();
        btnInsertar = new javax.swing.JButton();
        btnDescartar = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTituloDePagina.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        lblTituloDePagina.setText("Nuevo préstamo");
        lblTituloDePagina.setPreferredSize(new java.awt.Dimension(200, 30));
        add(lblTituloDePagina, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 10, -1, -1));

        txtIdentificacion.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        txtIdentificacion.setPreferredSize(new java.awt.Dimension(285, 30));
        add(txtIdentificacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, -1, -1));

        txtPrestamo.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        txtPrestamo.setPreferredSize(new java.awt.Dimension(285, 30));
        add(txtPrestamo, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, -1, -1));

        txtIsbn.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        txtIsbn.setPreferredSize(new java.awt.Dimension(285, 30));
        add(txtIsbn, new org.netbeans.lib.awtextra.AbsoluteConstraints(455, 110, -1, -1));

        txtEntrega.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        txtEntrega.setPreferredSize(new java.awt.Dimension(285, 30));
        add(txtEntrega, new org.netbeans.lib.awtextra.AbsoluteConstraints(455, 180, -1, -1));

        lblIsbn.setFont(new java.awt.Font("sansserif", 0, 12)); // NOI18N
        lblIsbn.setText("ISBN del libro");
        lblIsbn.setPreferredSize(new java.awt.Dimension(285, 15));
        add(lblIsbn, new org.netbeans.lib.awtextra.AbsoluteConstraints(455, 90, -1, -1));

        lblIdentificacion.setFont(new java.awt.Font("sansserif", 0, 12)); // NOI18N
        lblIdentificacion.setText("Documento del usuario");
        lblIdentificacion.setPreferredSize(new java.awt.Dimension(285, 15));
        add(lblIdentificacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, -1, -1));

        lblPrestamo.setFont(new java.awt.Font("sansserif", 0, 12)); // NOI18N
        lblPrestamo.setText("Fecha de préstamo");
        lblPrestamo.setPreferredSize(new java.awt.Dimension(285, 15));
        add(lblPrestamo, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, -1, -1));

        lblEntregar.setFont(new java.awt.Font("sansserif", 0, 12)); // NOI18N
        lblEntregar.setText("Fecha de entrega");
        lblEntregar.setPreferredSize(new java.awt.Dimension(285, 15));
        add(lblEntregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(455, 160, -1, -1));

        btnInsertar.setBackground(new java.awt.Color(204, 204, 255));
        btnInsertar.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        btnInsertar.setText("Insertar");
        btnInsertar.setBorder(null);
        btnInsertar.setPreferredSize(new java.awt.Dimension(90, 30));
        btnInsertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertarActionPerformed(evt);
            }
        });
        add(btnInsertar, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 345, -1, -1));

        btnDescartar.setBackground(new java.awt.Color(204, 204, 255));
        btnDescartar.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        btnDescartar.setText("Descartar");
        btnDescartar.setBorder(null);
        btnDescartar.setPreferredSize(new java.awt.Dimension(90, 30));
        btnDescartar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDescartarActionPerformed(evt);
            }
        });
        add(btnDescartar, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 345, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnInsertarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnInsertarActionPerformed
        // TODO add your handling code here:
        LibraryView.mostrarJPanel(new LoanView());
    }// GEN-LAST:event_btnInsertarActionPerformed

    private void btnDescartarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnDescartarActionPerformed
        // TODO add your handling code here:
        LibraryView.mostrarJPanel(new LoanView());
    }// GEN-LAST:event_btnDescartarActionPerformed

    public void cambiarTitulo(String nuevoTitulo) {
        lblTituloDePagina.setText(nuevoTitulo);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDescartar;
    private javax.swing.JButton btnInsertar;
    private javax.swing.JLabel lblEntregar;
    private javax.swing.JLabel lblIdentificacion;
    private javax.swing.JLabel lblIsbn;
    private javax.swing.JLabel lblPrestamo;
    private javax.swing.JLabel lblTituloDePagina;
    private javax.swing.JTextField txtEntrega;
    private javax.swing.JTextField txtIdentificacion;
    private javax.swing.JTextField txtIsbn;
    private javax.swing.JTextField txtPrestamo;
    // End of variables declaration//GEN-END:variables
}
