/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.biblioteca.view;

import javax.swing.JButton;

/**
 *
 * @author me
 */
public class InsertUserView extends javax.swing.JPanel {

    /**
     * Creates new form UserUpView
     */
    public InsertUserView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTituloDePagina = new javax.swing.JLabel();
        txtDireccion = new javax.swing.JTextField();
        txtIdentificacion = new javax.swing.JTextField();
        txtNombres = new javax.swing.JTextField();
        txtApellidos = new javax.swing.JTextField();
        txtCorreo = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        lblCorreo = new javax.swing.JLabel();
        lblIdentificacion = new javax.swing.JLabel();
        lblNombres = new javax.swing.JLabel();
        lblTelefono = new javax.swing.JLabel();
        lblDireccion = new javax.swing.JLabel();
        lblApellido = new javax.swing.JLabel();
        btnInsertar = new javax.swing.JButton();
        btnDescartar = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTituloDePagina.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        lblTituloDePagina.setText("Nuevo usuario");
        lblTituloDePagina.setPreferredSize(new java.awt.Dimension(200, 30));
        add(lblTituloDePagina, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 10, -1, -1));

        txtDireccion.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        txtDireccion.setPreferredSize(new java.awt.Dimension(285, 30));
        add(txtDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(455, 250, -1, -1));

        txtIdentificacion.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        txtIdentificacion.setPreferredSize(new java.awt.Dimension(285, 30));
        add(txtIdentificacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, -1, -1));

        txtNombres.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        txtNombres.setPreferredSize(new java.awt.Dimension(285, 30));
        add(txtNombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, -1, -1));

        txtApellidos.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        txtApellidos.setPreferredSize(new java.awt.Dimension(285, 30));
        add(txtApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 250, -1, -1));

        txtCorreo.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        txtCorreo.setPreferredSize(new java.awt.Dimension(285, 30));
        add(txtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(455, 110, -1, -1));

        txtTelefono.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        txtTelefono.setPreferredSize(new java.awt.Dimension(285, 30));
        add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(455, 180, -1, -1));

        lblCorreo.setFont(new java.awt.Font("sansserif", 0, 12)); // NOI18N
        lblCorreo.setText("Correo electrónico");
        lblCorreo.setPreferredSize(new java.awt.Dimension(285, 15));
        add(lblCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(455, 90, -1, -1));

        lblIdentificacion.setFont(new java.awt.Font("sansserif", 0, 12)); // NOI18N
        lblIdentificacion.setText("Documento de identificación");
        lblIdentificacion.setPreferredSize(new java.awt.Dimension(285, 15));
        add(lblIdentificacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, -1, -1));

        lblNombres.setFont(new java.awt.Font("sansserif", 0, 12)); // NOI18N
        lblNombres.setText("Nombres");
        lblNombres.setPreferredSize(new java.awt.Dimension(285, 15));
        add(lblNombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, -1, -1));

        lblTelefono.setFont(new java.awt.Font("sansserif", 0, 12)); // NOI18N
        lblTelefono.setText("Número de teléfono");
        lblTelefono.setPreferredSize(new java.awt.Dimension(285, 15));
        add(lblTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(455, 160, -1, -1));

        lblDireccion.setFont(new java.awt.Font("sansserif", 0, 12)); // NOI18N
        lblDireccion.setText("Dirección");
        lblDireccion.setPreferredSize(new java.awt.Dimension(285, 15));
        add(lblDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(455, 230, -1, -1));

        lblApellido.setFont(new java.awt.Font("sansserif", 0, 12)); // NOI18N
        lblApellido.setText("Apellidos");
        lblApellido.setPreferredSize(new java.awt.Dimension(285, 15));
        add(lblApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, -1, -1));

        btnInsertar.setBackground(new java.awt.Color(204, 204, 255));
        btnInsertar.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        btnInsertar.setText("Insertar");
        btnInsertar.setBorder(null);
        btnInsertar.setPreferredSize(new java.awt.Dimension(90, 30));
        add(btnInsertar, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 345, -1, -1));

        btnDescartar.setBackground(new java.awt.Color(204, 204, 255));
        btnDescartar.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        btnDescartar.setText("Descartar");
        btnDescartar.setBorder(null);
        btnDescartar.setPreferredSize(new java.awt.Dimension(90, 30));
        add(btnDescartar, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 345, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    public String getTxtIdentificacion() {
        return txtIdentificacion.getText();
    }

    public String getTxtNombres() {
        return txtNombres.getText();
    }

    public String getTxtApellidos() {
        return txtApellidos.getText();
    }

    public String getTxtCorreo() {
        return txtCorreo.getText();
    }

    public long getTxtTelefono() {
        return Long.parseLong(txtTelefono.getText());
    }

    public String getTxtDireccion() {
        return txtDireccion.getText();
    }
    
    public String getLblTituloDePagina() {
        return lblTituloDePagina.getText();
    }
    
    public JButton getBtnInsertar() {
        return btnInsertar;
    }
    
    public JButton getBtnDescartar() {
        return btnDescartar;
    }

    public void setTxtIdentificacion(String identificacion) {
        txtIdentificacion.setText(identificacion);
    }

    public void setEditableTxtIdentificacion(boolean opcion) {
        txtIdentificacion.setEditable(opcion);
    }

    public void setTxtNombres(String nombres) {
        txtNombres.setText(nombres);
    }

    public void setTxtApellidos(String apellidos) {
        txtApellidos.setText(apellidos);
    }

    public void setTxtCorreo(String correo) {
        txtCorreo.setText(correo);
    }

    public void setTxtTelefono(long telefono) {
        txtTelefono.setText(String.valueOf(telefono));
    }

    public void setTxtDireccion(String direccion) {
        txtDireccion.setText(direccion);
    }
    
    public void setLblTituloDePagina(String tituloDePagina) {
        lblTituloDePagina.setText(tituloDePagina);
    }
    
    public void clearJTextFields() {
        txtIdentificacion.setText("");
        txtNombres.setText("");
        txtApellidos.setText("");
        txtDireccion.setText("");
        txtTelefono.setText("");
        txtCorreo.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDescartar;
    private javax.swing.JButton btnInsertar;
    private javax.swing.JLabel lblApellido;
    private javax.swing.JLabel lblCorreo;
    private javax.swing.JLabel lblDireccion;
    private javax.swing.JLabel lblIdentificacion;
    private javax.swing.JLabel lblNombres;
    private javax.swing.JLabel lblTelefono;
    private javax.swing.JLabel lblTituloDePagina;
    private javax.swing.JTextField txtApellidos;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtIdentificacion;
    private javax.swing.JTextField txtNombres;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
