/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.biblioteca.view;

/**
 *
 * @author me
 */
public class InsertBookView extends javax.swing.JPanel {

    /**
     * Creates new form InsertBookView
     */
    public InsertBookView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTituloDePagina = new javax.swing.JLabel();
        txtEdicion = new javax.swing.JTextField();
        txtIsbn = new javax.swing.JTextField();
        txtTitulo = new javax.swing.JTextField();
        txtAutor = new javax.swing.JTextField();
        txtEditorial = new javax.swing.JTextField();
        txtGenero = new javax.swing.JTextField();
        lblEditorial = new javax.swing.JLabel();
        lblIsbn = new javax.swing.JLabel();
        lblTitulo = new javax.swing.JLabel();
        lblGenero = new javax.swing.JLabel();
        lblEdicion = new javax.swing.JLabel();
        lblAutor = new javax.swing.JLabel();
        btnInsertar = new javax.swing.JButton();
        btnDescartar = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTituloDePagina.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        lblTituloDePagina.setText("Nuevo libro");
        lblTituloDePagina.setPreferredSize(new java.awt.Dimension(200, 30));
        add(lblTituloDePagina, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 10, -1, -1));

        txtEdicion.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        txtEdicion.setPreferredSize(new java.awt.Dimension(285, 30));
        add(txtEdicion, new org.netbeans.lib.awtextra.AbsoluteConstraints(455, 250, -1, -1));

        txtIsbn.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        txtIsbn.setPreferredSize(new java.awt.Dimension(285, 30));
        add(txtIsbn, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, -1, -1));

        txtTitulo.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        txtTitulo.setPreferredSize(new java.awt.Dimension(285, 30));
        add(txtTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, -1, -1));

        txtAutor.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        txtAutor.setPreferredSize(new java.awt.Dimension(285, 30));
        add(txtAutor, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 250, -1, -1));

        txtEditorial.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        txtEditorial.setPreferredSize(new java.awt.Dimension(285, 30));
        add(txtEditorial, new org.netbeans.lib.awtextra.AbsoluteConstraints(455, 110, -1, -1));

        txtGenero.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        txtGenero.setPreferredSize(new java.awt.Dimension(285, 30));
        add(txtGenero, new org.netbeans.lib.awtextra.AbsoluteConstraints(455, 180, -1, -1));

        lblEditorial.setFont(new java.awt.Font("sansserif", 0, 12)); // NOI18N
        lblEditorial.setText("Editorial");
        lblEditorial.setPreferredSize(new java.awt.Dimension(285, 15));
        add(lblEditorial, new org.netbeans.lib.awtextra.AbsoluteConstraints(455, 90, -1, -1));

        lblIsbn.setFont(new java.awt.Font("sansserif", 0, 12)); // NOI18N
        lblIsbn.setText("Número ISBN");
        lblIsbn.setPreferredSize(new java.awt.Dimension(285, 15));
        add(lblIsbn, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, -1, -1));

        lblTitulo.setFont(new java.awt.Font("sansserif", 0, 12)); // NOI18N
        lblTitulo.setText("Título del libro");
        lblTitulo.setPreferredSize(new java.awt.Dimension(285, 15));
        add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, -1, -1));

        lblGenero.setFont(new java.awt.Font("sansserif", 0, 12)); // NOI18N
        lblGenero.setText("Género literario");
        lblGenero.setPreferredSize(new java.awt.Dimension(285, 15));
        add(lblGenero, new org.netbeans.lib.awtextra.AbsoluteConstraints(455, 160, -1, -1));

        lblEdicion.setFont(new java.awt.Font("sansserif", 0, 12)); // NOI18N
        lblEdicion.setText("Edición del libro");
        lblEdicion.setPreferredSize(new java.awt.Dimension(285, 15));
        add(lblEdicion, new org.netbeans.lib.awtextra.AbsoluteConstraints(455, 230, -1, -1));

        lblAutor.setFont(new java.awt.Font("sansserif", 0, 12)); // NOI18N
        lblAutor.setText("Nombre del autor");
        lblAutor.setPreferredSize(new java.awt.Dimension(285, 15));
        add(lblAutor, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, -1, -1));

        btnInsertar.setBackground(new java.awt.Color(204, 204, 255));
        btnInsertar.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        btnInsertar.setText("Insertar");
        btnInsertar.setBorder(null);
        btnInsertar.setPreferredSize(new java.awt.Dimension(90, 30));
        btnInsertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertarActionPerformed(evt);
            }
        });
        add(btnInsertar, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 345, -1, -1));

        btnDescartar.setBackground(new java.awt.Color(204, 204, 255));
        btnDescartar.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        btnDescartar.setText("Descartar");
        btnDescartar.setBorder(null);
        btnDescartar.setPreferredSize(new java.awt.Dimension(90, 30));
        btnDescartar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDescartarActionPerformed(evt);
            }
        });
        add(btnDescartar, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 345, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnInsertarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnInsertarActionPerformed
        // TODO add your handling code here:
        LibraryView.mostrarJPanel(new BookView());
    }// GEN-LAST:event_btnInsertarActionPerformed

    private void btnDescartarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnDescartarActionPerformed
        // TODO add your handling code here:
        LibraryView.mostrarJPanel(new BookView());
    }// GEN-LAST:event_btnDescartarActionPerformed

    public void cambiarTitulo(String nuevoTitulo) {
        lblTituloDePagina.setText(nuevoTitulo);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDescartar;
    private javax.swing.JButton btnInsertar;
    private javax.swing.JLabel lblAutor;
    private javax.swing.JLabel lblEdicion;
    private javax.swing.JLabel lblEditorial;
    private javax.swing.JLabel lblGenero;
    private javax.swing.JLabel lblIsbn;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblTituloDePagina;
    private javax.swing.JTextField txtAutor;
    private javax.swing.JTextField txtEdicion;
    private javax.swing.JTextField txtEditorial;
    private javax.swing.JTextField txtGenero;
    private javax.swing.JTextField txtIsbn;
    private javax.swing.JTextField txtTitulo;
    // End of variables declaration//GEN-END:variables
}
