/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.biblioteca.view;

/**
 *
 * @author me
 */
public class InsertPenaltyView extends javax.swing.JPanel {

    /**
     * Creates new form InsertPenaltyView
     */
    public InsertPenaltyView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTituloDePagina = new javax.swing.JLabel();
        txtIdentificacion = new javax.swing.JTextField();
        txtAmonestacion = new javax.swing.JTextField();
        lblAmonestacion = new javax.swing.JLabel();
        lblIdentificacion = new javax.swing.JLabel();
        lblRazon = new javax.swing.JLabel();
        lblNota = new javax.swing.JLabel();
        btnInsertar = new javax.swing.JButton();
        btnDescartar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtRazon = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtNota = new javax.swing.JTextArea();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTituloDePagina.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        lblTituloDePagina.setText("Nueva penalización");
        lblTituloDePagina.setPreferredSize(new java.awt.Dimension(200, 30));
        add(lblTituloDePagina, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 10, -1, -1));

        txtIdentificacion.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        txtIdentificacion.setPreferredSize(new java.awt.Dimension(285, 30));
        add(txtIdentificacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, -1, -1));

        txtAmonestacion.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        txtAmonestacion.setPreferredSize(new java.awt.Dimension(285, 30));
        add(txtAmonestacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(455, 110, -1, -1));

        lblAmonestacion.setFont(new java.awt.Font("sansserif", 0, 12)); // NOI18N
        lblAmonestacion.setText("Amonestación económica");
        lblAmonestacion.setPreferredSize(new java.awt.Dimension(285, 15));
        add(lblAmonestacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(455, 90, -1, -1));

        lblIdentificacion.setFont(new java.awt.Font("sansserif", 0, 12)); // NOI18N
        lblIdentificacion.setText("Documento de identificación");
        lblIdentificacion.setPreferredSize(new java.awt.Dimension(285, 15));
        add(lblIdentificacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, -1, -1));

        lblRazon.setFont(new java.awt.Font("sansserif", 0, 12)); // NOI18N
        lblRazon.setText("Razón de la amonestación");
        lblRazon.setPreferredSize(new java.awt.Dimension(285, 15));
        add(lblRazon, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, -1, -1));

        lblNota.setFont(new java.awt.Font("sansserif", 0, 12)); // NOI18N
        lblNota.setText("Nota adiccional");
        lblNota.setPreferredSize(new java.awt.Dimension(285, 15));
        add(lblNota, new org.netbeans.lib.awtextra.AbsoluteConstraints(455, 160, -1, -1));

        btnInsertar.setBackground(new java.awt.Color(204, 204, 255));
        btnInsertar.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        btnInsertar.setText("Insertar");
        btnInsertar.setBorder(null);
        btnInsertar.setPreferredSize(new java.awt.Dimension(90, 30));
        btnInsertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertarActionPerformed(evt);
            }
        });
        add(btnInsertar, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 345, -1, -1));

        btnDescartar.setBackground(new java.awt.Color(204, 204, 255));
        btnDescartar.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        btnDescartar.setText("Descartar");
        btnDescartar.setBorder(null);
        btnDescartar.setPreferredSize(new java.awt.Dimension(90, 30));
        btnDescartar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDescartarActionPerformed(evt);
            }
        });
        add(btnDescartar, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 345, -1, -1));

        txtRazon.setColumns(20);
        txtRazon.setRows(5);
        jScrollPane1.setViewportView(txtRazon);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, 280, 110));

        txtNota.setColumns(20);
        txtNota.setRows(5);
        jScrollPane3.setViewportView(txtNota);

        add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(455, 180, 285, 110));
    }// </editor-fold>//GEN-END:initComponents

    private void btnInsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertarActionPerformed
        // TODO add your handling code here:
        LibraryView.mostrarJPanel(new PenaltyView());
    }//GEN-LAST:event_btnInsertarActionPerformed

    private void btnDescartarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDescartarActionPerformed
        // TODO add your handling code here:
        LibraryView.mostrarJPanel(new PenaltyView());
    }//GEN-LAST:event_btnDescartarActionPerformed

    public void cambiarTitulo(String nuevoTitulo) {
        lblTituloDePagina.setText(nuevoTitulo);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDescartar;
    private javax.swing.JButton btnInsertar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblAmonestacion;
    private javax.swing.JLabel lblIdentificacion;
    private javax.swing.JLabel lblNota;
    private javax.swing.JLabel lblRazon;
    private javax.swing.JLabel lblTituloDePagina;
    private javax.swing.JTextField txtAmonestacion;
    private javax.swing.JTextField txtIdentificacion;
    private javax.swing.JTextArea txtNota;
    private javax.swing.JTextArea txtRazon;
    // End of variables declaration//GEN-END:variables
}
