/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.biblioteca.view;

import java.awt.BorderLayout;
import javax.swing.JPanel;

/**
 *
 * @author me
 */
public class LibraryView extends javax.swing.JFrame {

    /**
     * Creates new form LibraryView
     */
    public LibraryView() {
        initComponents();
        setLocationRelativeTo(null);
        mostrarJPanel(new WelcomeView());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlOpciones = new javax.swing.JPanel();
        btnInicio = new javax.swing.JButton();
        btnUsuarios = new javax.swing.JButton();
        btnLibros = new javax.swing.JButton();
        btnPrestamos = new javax.swing.JButton();
        btnPenalizaciones = new javax.swing.JButton();
        pnlContenido = new javax.swing.JPanel();
        pnlBarra = new javax.swing.JPanel();
        btnCerrarSesion = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Biblioteca");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlOpciones.setBackground(new java.awt.Color(204, 204, 255));
        pnlOpciones.setPreferredSize(new java.awt.Dimension(220, 590));
        pnlOpciones.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnInicio.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        btnInicio.setText("Inicio");
        btnInicio.setBorder(null);
        btnInicio.setBorderPainted(false);
        btnInicio.setContentAreaFilled(false);
        btnInicio.setFocusPainted(false);
        btnInicio.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnInicio.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnInicio.setPreferredSize(new java.awt.Dimension(180, 50));
        btnInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInicioActionPerformed(evt);
            }
        });
        pnlOpciones.add(btnInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 220, -1));

        btnUsuarios.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        btnUsuarios.setText("Usuarios");
        btnUsuarios.setBorder(null);
        btnUsuarios.setBorderPainted(false);
        btnUsuarios.setContentAreaFilled(false);
        btnUsuarios.setFocusPainted(false);
        btnUsuarios.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnUsuarios.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnUsuarios.setPreferredSize(new java.awt.Dimension(180, 50));
        btnUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsuariosActionPerformed(evt);
            }
        });
        pnlOpciones.add(btnUsuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 220, -1));

        btnLibros.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        btnLibros.setText("Libros");
        btnLibros.setBorder(null);
        btnLibros.setBorderPainted(false);
        btnLibros.setContentAreaFilled(false);
        btnLibros.setFocusPainted(false);
        btnLibros.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnLibros.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnLibros.setPreferredSize(new java.awt.Dimension(180, 50));
        btnLibros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLibrosActionPerformed(evt);
            }
        });
        pnlOpciones.add(btnLibros, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 220, -1));

        btnPrestamos.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        btnPrestamos.setText("Préstamos");
        btnPrestamos.setBorder(null);
        btnPrestamos.setBorderPainted(false);
        btnPrestamos.setContentAreaFilled(false);
        btnPrestamos.setFocusPainted(false);
        btnPrestamos.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnPrestamos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPrestamos.setPreferredSize(new java.awt.Dimension(180, 50));
        btnPrestamos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrestamosActionPerformed(evt);
            }
        });
        pnlOpciones.add(btnPrestamos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 220, -1));

        btnPenalizaciones.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        btnPenalizaciones.setText("Penalizaciones");
        btnPenalizaciones.setBorder(null);
        btnPenalizaciones.setBorderPainted(false);
        btnPenalizaciones.setContentAreaFilled(false);
        btnPenalizaciones.setFocusPainted(false);
        btnPenalizaciones.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnPenalizaciones.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPenalizaciones.setPreferredSize(new java.awt.Dimension(180, 50));
        btnPenalizaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPenalizacionesActionPerformed(evt);
            }
        });
        pnlOpciones.add(btnPenalizaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, 220, -1));

        getContentPane().add(pnlOpciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pnlContenido.setBackground(new java.awt.Color(255, 255, 255));
        pnlContenido.setLayout(new java.awt.BorderLayout());
        getContentPane().add(pnlContenido, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 140, 830, 450));

        pnlBarra.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCerrarSesion.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        btnCerrarSesion.setText("Cerrar sesión");
        btnCerrarSesion.setBorder(null);
        btnCerrarSesion.setPreferredSize(new java.awt.Dimension(125, 30));
        btnCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarSesionActionPerformed(evt);
            }
        });
        pnlBarra.add(btnCerrarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 10, -1, -1));

        getContentPane().add(pnlBarra, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 0, 830, 140));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarSesionActionPerformed
        // TODO add your handling code here:
        javax.swing.JOptionPane.showMessageDialog(this, "Sesión cerrada", "._.", 1);
        this.dispose();
        new LoginView().setVisible(true);
    }//GEN-LAST:event_btnCerrarSesionActionPerformed

    private void btnUsuariosActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnUsuariosActionPerformed
        // TODO add your handling code here:
        mostrarJPanel(new UserView().getPnlVerUsuario());
    }// GEN-LAST:event_btnUsuariosActionPerformed

    private void btnLibrosActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnLibrosActionPerformed
        // TODO add your handling code here:
        mostrarJPanel(new BookView().getPnlVerLibro());
    }// GEN-LAST:event_btnLibrosActionPerformed

    private void btnPrestamosActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnPrestamosActionPerformed
        // TODO add your handling code here:
        mostrarJPanel(new LoanView().getPnlVerPrestamo());
    }// GEN-LAST:event_btnPrestamosActionPerformed

    private void btnPenalizacionesActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnPenalizacionesActionPerformed
        // TODO add your handling code here:
        mostrarJPanel(new PenaltyView().getPnlVerPenalizacion());
    }// GEN-LAST:event_btnPenalizacionesActionPerformed

    private void btnInicioActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnInicioActionPerformed
        // TODO add your handling code here:
        mostrarJPanel(new WelcomeView());
    }// GEN-LAST:event_btnInicioActionPerformed

    public static void mostrarJPanel(JPanel panel) {
        panel.setSize(830, 450);
        panel.setLocation(0, 0);

        pnlContenido.removeAll();
        pnlContenido.add(panel, BorderLayout.CENTER);
        pnlContenido.revalidate();
        pnlContenido.repaint();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LibraryView.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LibraryView.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LibraryView.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LibraryView.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LibraryView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrarSesion;
    private javax.swing.JButton btnInicio;
    private javax.swing.JButton btnLibros;
    private javax.swing.JButton btnPenalizaciones;
    private javax.swing.JButton btnPrestamos;
    private javax.swing.JButton btnUsuarios;
    private javax.swing.JPanel pnlBarra;
    private static javax.swing.JPanel pnlContenido;
    private javax.swing.JPanel pnlOpciones;
    // End of variables declaration//GEN-END:variables
}
