/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.biblioteca.view;

import com.biblioteca.controller.LoanController;
import com.biblioteca.model.LoanModel;
import static com.biblioteca.view.LibraryView.mostrarJPanel;
import java.time.LocalDate;
import javax.swing.JButton;
import javax.swing.JPanel;
import javax.swing.JTable;

/**
 *
 * @author me
 */
public class LoanView extends javax.swing.JPanel {
    
    private final LoanController loanController;

    /**
     * Creates new form LoanView
     */
    public LoanView() {
        initComponents();
        loanController = new LoanController(this, new LoanModel());
        loanController.loadTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlVerPrestamo = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDatos = new javax.swing.JTable();
        btnEditar = new javax.swing.JButton();
        btnEntrega = new javax.swing.JButton();
        txtBuscar = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        lblTituloVerPrestamo = new javax.swing.JLabel();
        pnlDatosPrestamo = new javax.swing.JPanel();
        lblTituloDatosPrestamo = new javax.swing.JLabel();
        txtIdentificacion = new javax.swing.JTextField();
        txtPrestamo = new javax.swing.JTextField();
        txtIsbn = new javax.swing.JTextField();
        txtEntrega = new javax.swing.JTextField();
        lblIsbn = new javax.swing.JLabel();
        lblIdentificacion = new javax.swing.JLabel();
        lblPrestamo = new javax.swing.JLabel();
        lblEntregar = new javax.swing.JLabel();
        btnInsertar = new javax.swing.JButton();
        btnDescartar = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlVerPrestamo.setBackground(new java.awt.Color(255, 255, 255));
        pnlVerPrestamo.setPreferredSize(new java.awt.Dimension(830, 450));
        pnlVerPrestamo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblDatos.setFont(new java.awt.Font("sansserif", 0, 12)); // NOI18N
        tblDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Identificación del usuario", "ISBN prestado", "Fecha de préstamo", "Fecha de entrega"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblDatos.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tblDatos.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tblDatos);
        if (tblDatos.getColumnModel().getColumnCount() > 0) {
            tblDatos.getColumnModel().getColumn(0).setResizable(false);
            tblDatos.getColumnModel().getColumn(1).setResizable(false);
            tblDatos.getColumnModel().getColumn(2).setResizable(false);
            tblDatos.getColumnModel().getColumn(3).setResizable(false);
        }

        pnlVerPrestamo.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 57, 818, 338));

        btnEditar.setBackground(new java.awt.Color(204, 204, 255));
        btnEditar.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        btnEditar.setText("Editar");
        btnEditar.setBorder(null);
        btnEditar.setPreferredSize(new java.awt.Dimension(90, 30));
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        pnlVerPrestamo.add(btnEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(634, 410, -1, -1));

        btnEntrega.setBackground(new java.awt.Color(204, 204, 255));
        btnEntrega.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        btnEntrega.setText("Entrega");
        btnEntrega.setBorder(null);
        btnEntrega.setPreferredSize(new java.awt.Dimension(90, 30));
        btnEntrega.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntregaActionPerformed(evt);
            }
        });
        pnlVerPrestamo.add(btnEntrega, new org.netbeans.lib.awtextra.AbsoluteConstraints(734, 410, -1, -1));

        txtBuscar.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        txtBuscar.setMinimumSize(new java.awt.Dimension(64, 30));
        txtBuscar.setPreferredSize(new java.awt.Dimension(300, 30));
        pnlVerPrestamo.add(txtBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(534, 12, 185, -1));

        btnBuscar.setBackground(new java.awt.Color(204, 204, 255));
        btnBuscar.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.setBorder(null);
        btnBuscar.setPreferredSize(new java.awt.Dimension(90, 30));
        pnlVerPrestamo.add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(734, 12, -1, -1));

        lblTituloVerPrestamo.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        lblTituloVerPrestamo.setText("Préstamos");
        lblTituloVerPrestamo.setPreferredSize(new java.awt.Dimension(100, 30));
        pnlVerPrestamo.add(lblTituloVerPrestamo, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 10, -1, -1));

        add(pnlVerPrestamo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pnlDatosPrestamo.setBackground(new java.awt.Color(255, 255, 255));
        pnlDatosPrestamo.setPreferredSize(new java.awt.Dimension(830, 450));
        pnlDatosPrestamo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTituloDatosPrestamo.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        lblTituloDatosPrestamo.setPreferredSize(new java.awt.Dimension(200, 30));
        pnlDatosPrestamo.add(lblTituloDatosPrestamo, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 10, -1, -1));

        txtIdentificacion.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        txtIdentificacion.setPreferredSize(new java.awt.Dimension(285, 30));
        pnlDatosPrestamo.add(txtIdentificacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, -1, -1));

        txtPrestamo.setEditable(false);
        txtPrestamo.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        txtPrestamo.setPreferredSize(new java.awt.Dimension(285, 30));
        pnlDatosPrestamo.add(txtPrestamo, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, -1, -1));

        txtIsbn.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        txtIsbn.setPreferredSize(new java.awt.Dimension(285, 30));
        pnlDatosPrestamo.add(txtIsbn, new org.netbeans.lib.awtextra.AbsoluteConstraints(455, 110, -1, -1));

        txtEntrega.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        txtEntrega.setPreferredSize(new java.awt.Dimension(285, 30));
        pnlDatosPrestamo.add(txtEntrega, new org.netbeans.lib.awtextra.AbsoluteConstraints(455, 180, -1, -1));

        lblIsbn.setFont(new java.awt.Font("sansserif", 0, 12)); // NOI18N
        lblIsbn.setText("ISBN del libro");
        lblIsbn.setPreferredSize(new java.awt.Dimension(285, 15));
        pnlDatosPrestamo.add(lblIsbn, new org.netbeans.lib.awtextra.AbsoluteConstraints(455, 90, -1, -1));

        lblIdentificacion.setFont(new java.awt.Font("sansserif", 0, 12)); // NOI18N
        lblIdentificacion.setText("Documento del usuario");
        lblIdentificacion.setPreferredSize(new java.awt.Dimension(285, 15));
        pnlDatosPrestamo.add(lblIdentificacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, -1, -1));

        lblPrestamo.setFont(new java.awt.Font("sansserif", 0, 12)); // NOI18N
        lblPrestamo.setText("Fecha de préstamo");
        lblPrestamo.setPreferredSize(new java.awt.Dimension(285, 15));
        pnlDatosPrestamo.add(lblPrestamo, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, -1, -1));

        lblEntregar.setFont(new java.awt.Font("sansserif", 0, 12)); // NOI18N
        lblEntregar.setText("Fecha de entrega");
        lblEntregar.setPreferredSize(new java.awt.Dimension(285, 15));
        pnlDatosPrestamo.add(lblEntregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(455, 160, -1, -1));

        btnInsertar.setBackground(new java.awt.Color(204, 204, 255));
        btnInsertar.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        btnInsertar.setBorder(null);
        btnInsertar.setPreferredSize(new java.awt.Dimension(90, 30));
        pnlDatosPrestamo.add(btnInsertar, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 345, -1, -1));

        btnDescartar.setBackground(new java.awt.Color(204, 204, 255));
        btnDescartar.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        btnDescartar.setText("Descartar");
        btnDescartar.setBorder(null);
        btnDescartar.setPreferredSize(new java.awt.Dimension(90, 30));
        btnDescartar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDescartarActionPerformed(evt);
            }
        });
        pnlDatosPrestamo.add(btnDescartar, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 345, -1, -1));

        add(pnlDatosPrestamo, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnDescartarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDescartarActionPerformed
        // TODO add your handling code here:
        mostrarJPanel(new LoanView().getPnlVerPrestamo());
    }//GEN-LAST:event_btnDescartarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        // TODO add your handling code here:
        loanController.updateLoan();
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnEntregaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntregaActionPerformed
        // TODO add your handling code here:
        loanController.returnLoan();
    }//GEN-LAST:event_btnEntregaActionPerformed

    public JButton getBtnInsertar() {
        return btnInsertar;
    }

    public void setLblTituloDatosPrestamo(String titulo) {
        lblTituloDatosPrestamo.setText(titulo);
    }

    public JPanel getPnlDatosPrestamo() {
        return pnlDatosPrestamo;
    }

    public JPanel getPnlVerPrestamo() {
        return pnlVerPrestamo;
    }

    public JTable getTblDatos() {
        return tblDatos;
    }

    public LocalDate getTxtEntrega() {
        return LocalDate.parse(txtEntrega.getText());
    }

    public void setTxtEntrega(LocalDate entrega) {
        txtEntrega.setText(entrega.toString());
    }

    public String getTxtIdentificacion() {
        return txtIdentificacion.getText();
    }

    public void setTxtIdentificacion(String identificacion) {
        txtIdentificacion.setText(identificacion);
    }

    public String getTxtIsbn() {
        return txtIsbn.getText();
    }

    public void setTxtIsbn(String isbn) {
        txtIsbn.setText(isbn);
    }

    public LocalDate getTxtPrestamo() {
        return LocalDate.parse(txtPrestamo.getText());
    }

    public void setTxtPrestamo(LocalDate prestamo) {
        txtPrestamo.setText(prestamo.toString());
    }
    
    public void setEditableTxtIdentificacion(boolean opcion) {
        txtIdentificacion.setEditable(opcion);
    }
    
    public void setEditableTxtIsbn(boolean opcion) {
        txtIsbn.setEditable(opcion);
    }
    
    public void mostrarMensaje(String mensaje) {
        javax.swing.JOptionPane.showMessageDialog(this, mensaje);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnDescartar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEntrega;
    private javax.swing.JButton btnInsertar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblEntregar;
    private javax.swing.JLabel lblIdentificacion;
    private javax.swing.JLabel lblIsbn;
    private javax.swing.JLabel lblPrestamo;
    private javax.swing.JLabel lblTituloDatosPrestamo;
    private javax.swing.JLabel lblTituloVerPrestamo;
    private javax.swing.JPanel pnlDatosPrestamo;
    private javax.swing.JPanel pnlVerPrestamo;
    private javax.swing.JTable tblDatos;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtEntrega;
    private javax.swing.JTextField txtIdentificacion;
    private javax.swing.JTextField txtIsbn;
    private javax.swing.JTextField txtPrestamo;
    // End of variables declaration//GEN-END:variables
}
