/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.biblioteca.view;

import com.biblioteca.controller.UserController;
import com.biblioteca.model.UserModel;
import static com.biblioteca.view.LibraryView.mostrarJPanel;
import javax.swing.JButton;
import javax.swing.JPanel;
import javax.swing.JTable;

/**
 *
 * @author me
 */
public class UserView extends javax.swing.JPanel {
    
    private final UserController userController;

    /**
     * Creates new form UserView
     */
    public UserView() {
        initComponents();
        userController = new UserController(this, new UserModel());
        userController.loadTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlVerUsuario = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDatos = new javax.swing.JTable();
        btnEditar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        txtBuscar = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        lblTituloVerUsuario = new javax.swing.JLabel();
        btnNuevo = new javax.swing.JButton();
        pnlDatosUsuario = new javax.swing.JPanel();
        lblTituloDatosUsuario = new javax.swing.JLabel();
        txtDireccion = new javax.swing.JTextField();
        txtIdentificacion = new javax.swing.JTextField();
        txtNombres = new javax.swing.JTextField();
        txtApellidos = new javax.swing.JTextField();
        txtCorreo = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        lblCorreo = new javax.swing.JLabel();
        lblIdentificacion = new javax.swing.JLabel();
        lblNombres = new javax.swing.JLabel();
        lblTelefono = new javax.swing.JLabel();
        lblDireccion = new javax.swing.JLabel();
        lblApellido = new javax.swing.JLabel();
        btnInsertar = new javax.swing.JButton();
        btnDescartar = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlVerUsuario.setBackground(new java.awt.Color(255, 255, 255));
        pnlVerUsuario.setPreferredSize(new java.awt.Dimension(830, 450));
        pnlVerUsuario.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblDatos.setFont(new java.awt.Font("sansserif", 0, 12)); // NOI18N
        tblDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Identificación", "Nombres", "Apellidos", "Dirección", "Teléfono", "Correo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Long.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblDatos.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tblDatos.setFillsViewportHeight(true);
        tblDatos.setSelectionBackground(new java.awt.Color(153, 153, 255));
        tblDatos.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tblDatos.setShowGrid(true);
        tblDatos.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tblDatos);
        if (tblDatos.getColumnModel().getColumnCount() > 0) {
            tblDatos.getColumnModel().getColumn(0).setResizable(false);
            tblDatos.getColumnModel().getColumn(1).setResizable(false);
            tblDatos.getColumnModel().getColumn(2).setResizable(false);
            tblDatos.getColumnModel().getColumn(3).setResizable(false);
            tblDatos.getColumnModel().getColumn(4).setResizable(false);
            tblDatos.getColumnModel().getColumn(5).setResizable(false);
        }

        pnlVerUsuario.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 57, 818, 338));

        btnEditar.setBackground(new java.awt.Color(204, 204, 255));
        btnEditar.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        btnEditar.setText("Editar");
        btnEditar.setBorder(null);
        btnEditar.setPreferredSize(new java.awt.Dimension(90, 30));
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        pnlVerUsuario.add(btnEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(634, 410, -1, -1));

        btnEliminar.setBackground(new java.awt.Color(204, 204, 255));
        btnEliminar.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.setBorder(null);
        btnEliminar.setPreferredSize(new java.awt.Dimension(90, 30));
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        pnlVerUsuario.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(734, 410, -1, -1));

        txtBuscar.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        txtBuscar.setMinimumSize(new java.awt.Dimension(64, 30));
        txtBuscar.setPreferredSize(new java.awt.Dimension(300, 30));
        pnlVerUsuario.add(txtBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(534, 12, 185, -1));

        btnBuscar.setBackground(new java.awt.Color(204, 204, 255));
        btnBuscar.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.setBorder(null);
        btnBuscar.setPreferredSize(new java.awt.Dimension(90, 30));
        pnlVerUsuario.add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(734, 12, -1, -1));

        lblTituloVerUsuario.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        lblTituloVerUsuario.setText("Usuarios");
        lblTituloVerUsuario.setPreferredSize(new java.awt.Dimension(80, 30));
        pnlVerUsuario.add(lblTituloVerUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 10, -1, -1));

        btnNuevo.setBackground(new java.awt.Color(204, 204, 255));
        btnNuevo.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        btnNuevo.setText("Nuevo");
        btnNuevo.setBorder(null);
        btnNuevo.setPreferredSize(new java.awt.Dimension(90, 30));
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });
        pnlVerUsuario.add(btnNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(534, 410, -1, -1));

        add(pnlVerUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pnlDatosUsuario.setBackground(new java.awt.Color(255, 255, 255));
        pnlDatosUsuario.setPreferredSize(new java.awt.Dimension(830, 450));
        pnlDatosUsuario.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTituloDatosUsuario.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        lblTituloDatosUsuario.setPreferredSize(new java.awt.Dimension(200, 30));
        pnlDatosUsuario.add(lblTituloDatosUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 10, -1, -1));

        txtDireccion.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        txtDireccion.setPreferredSize(new java.awt.Dimension(285, 30));
        pnlDatosUsuario.add(txtDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(455, 250, -1, -1));

        txtIdentificacion.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        txtIdentificacion.setPreferredSize(new java.awt.Dimension(285, 30));
        pnlDatosUsuario.add(txtIdentificacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, -1, -1));

        txtNombres.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        txtNombres.setPreferredSize(new java.awt.Dimension(285, 30));
        pnlDatosUsuario.add(txtNombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, -1, -1));

        txtApellidos.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        txtApellidos.setPreferredSize(new java.awt.Dimension(285, 30));
        pnlDatosUsuario.add(txtApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 250, -1, -1));

        txtCorreo.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        txtCorreo.setPreferredSize(new java.awt.Dimension(285, 30));
        pnlDatosUsuario.add(txtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(455, 110, -1, -1));

        txtTelefono.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        txtTelefono.setPreferredSize(new java.awt.Dimension(285, 30));
        pnlDatosUsuario.add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(455, 180, -1, -1));

        lblCorreo.setFont(new java.awt.Font("sansserif", 0, 12)); // NOI18N
        lblCorreo.setText("Correo electrónico");
        lblCorreo.setPreferredSize(new java.awt.Dimension(285, 15));
        pnlDatosUsuario.add(lblCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(455, 90, -1, -1));

        lblIdentificacion.setFont(new java.awt.Font("sansserif", 0, 12)); // NOI18N
        lblIdentificacion.setText("Documento de identificación");
        lblIdentificacion.setPreferredSize(new java.awt.Dimension(285, 15));
        pnlDatosUsuario.add(lblIdentificacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, -1, -1));

        lblNombres.setFont(new java.awt.Font("sansserif", 0, 12)); // NOI18N
        lblNombres.setText("Nombres");
        lblNombres.setPreferredSize(new java.awt.Dimension(285, 15));
        pnlDatosUsuario.add(lblNombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, -1, -1));

        lblTelefono.setFont(new java.awt.Font("sansserif", 0, 12)); // NOI18N
        lblTelefono.setText("Número de teléfono");
        lblTelefono.setPreferredSize(new java.awt.Dimension(285, 15));
        pnlDatosUsuario.add(lblTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(455, 160, -1, -1));

        lblDireccion.setFont(new java.awt.Font("sansserif", 0, 12)); // NOI18N
        lblDireccion.setText("Dirección");
        lblDireccion.setPreferredSize(new java.awt.Dimension(285, 15));
        pnlDatosUsuario.add(lblDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(455, 230, -1, -1));

        lblApellido.setFont(new java.awt.Font("sansserif", 0, 12)); // NOI18N
        lblApellido.setText("Apellidos");
        lblApellido.setPreferredSize(new java.awt.Dimension(285, 15));
        pnlDatosUsuario.add(lblApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, -1, -1));

        btnInsertar.setBackground(new java.awt.Color(204, 204, 255));
        btnInsertar.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        btnInsertar.setBorder(null);
        btnInsertar.setPreferredSize(new java.awt.Dimension(90, 30));
        pnlDatosUsuario.add(btnInsertar, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 345, -1, -1));

        btnDescartar.setBackground(new java.awt.Color(204, 204, 255));
        btnDescartar.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        btnDescartar.setText("Descartar");
        btnDescartar.setBorder(null);
        btnDescartar.setPreferredSize(new java.awt.Dimension(90, 30));
        btnDescartar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDescartarActionPerformed(evt);
            }
        });
        pnlDatosUsuario.add(btnDescartar, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 345, -1, -1));

        add(pnlDatosUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        // TODO add your handling code here:
        userController.updateUser();
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        userController.deleteUser();
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        // TODO add your handling code here:
        userController.createUser();
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnDescartarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDescartarActionPerformed
        // TODO add your handling code here:
        mostrarJPanel(new UserView().getPnlVerUsuario());
    }//GEN-LAST:event_btnDescartarActionPerformed

    public void setTxtIdentificacion(String identificacion) {
        txtIdentificacion.setText(identificacion);
    }

    public void setEditableTxtIdentificacion(boolean opcion) {
        txtIdentificacion.setEditable(opcion);
    }

    public void setTxtNombres(String nombres) {
        txtNombres.setText(nombres);
    }

    public void setTxtApellidos(String apellidos) {
        txtApellidos.setText(apellidos);
    }

    public void setTxtCorreo(String correo) {
        txtCorreo.setText(correo);
    }

    public void setTxtTelefono(long telefono) {
        txtTelefono.setText(String.valueOf(telefono));
    }

    public void setTxtDireccion(String direccion) {
        txtDireccion.setText(direccion);
    }
    
    public String getTxtIdentificacion() {
        return txtIdentificacion.getText();
    }

    public String getTxtNombres() {
        return txtNombres.getText();
    }

    public String getTxtApellidos() {
        return txtApellidos.getText();
    }

    public String getTxtCorreo() {
        return txtCorreo.getText();
    }

    public long getTxtTelefono() {
        return Long.parseLong(txtTelefono.getText());
    }

    public String getTxtDireccion() {
        return txtDireccion.getText();
    }
    
    public void setLblTituloDatosUsuario(String titulo) {
        lblTituloDatosUsuario.setText(titulo);
    }
    
    public JPanel getPnlVerUsuario() {
        return pnlVerUsuario;
    }
    
    public JPanel getPnlDatosUsuario() {
        return pnlDatosUsuario;
    }
    
    public JTable getTblDatos() {
        return tblDatos;    
    }
    
    public JButton getBtnInsertar() {
        return btnInsertar;
    }

    public void mostrarMensaje(String mensaje) {
        javax.swing.JOptionPane.showMessageDialog(this, mensaje);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnDescartar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnInsertar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblApellido;
    private javax.swing.JLabel lblCorreo;
    private javax.swing.JLabel lblDireccion;
    private javax.swing.JLabel lblIdentificacion;
    private javax.swing.JLabel lblNombres;
    private javax.swing.JLabel lblTelefono;
    private javax.swing.JLabel lblTituloDatosUsuario;
    private javax.swing.JLabel lblTituloVerUsuario;
    private javax.swing.JPanel pnlDatosUsuario;
    private javax.swing.JPanel pnlVerUsuario;
    private javax.swing.JTable tblDatos;
    private javax.swing.JTextField txtApellidos;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtIdentificacion;
    private javax.swing.JTextField txtNombres;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
